
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2024 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "ximage_processing.h"

/*
* The configuration table for devices
*/

XImage_processing_Config XImage_processing_ConfigTable[XPAR_XIMAGE_PROCESSING_NUM_INSTANCES] =
{
	{
		XPAR_IMAGE_PROCESSING_0_DEVICE_ID,
		XPAR_IMAGE_PROCESSING_0_S_AXI_CONTROL_BASEADDR
	}
};


